### ISSUE TITLE
Request: Add the option to disable console logs

### ISSUE THREAD

**Issue by bcowell** [LIT-Protocol/CeramicIntegration#6]
No idea why these aren't disabled by default in a dist, but please add the option to silence them.

`lit-ceramic-sdk version: 1.1.13`

**Comment by glitch003** [comment]
Hey @bcowell , 

If you use the LitJsSdk by itself, without the ceramic integration, you can turn them off like this: 

```const litNodeClient = new LitJsSdk.LitNodeClient({debug: false})```

This is documented here under config: https://lit-protocol.github.io/lit-js-sdk/api_docs_html/

Unfortunately, this isn't possible in the CeramicIntegration package right now because passing config to the LitNodeClient isn't implemented.  So I think you have 2 options

1. Fork this project and add debug: false to the LitNodeClient connection here: https://github.com/LIT-Protocol/CeramicIntegration/blob/main/src/client.ts#L11
2. Use the LitJsSdk and Ceramic SDK and integrate them yourself.  If you look through the code in this repo, it's actually really small.  It just encrypts stuff with Lit before saving to Ceramic, and then decrypts after reading from Ceramic.  If you're building something that you will maintain for a long time, I would go this route, because Ceramic is growing and changing everyday and you won't have to wait for us to ship updates to the Ceramic SDK in this integration.
